import numpy
from Environnement import Environnement
from Objet import Robot

#tests
env=Environnement(10,10)
robot=Robot("droite")
env.afficheTab() #le tableau est vide
print()

robot.deposer(env,robot.x,robot.y) #on dépose le robot (en (0,0) par défaut)
print("Le robot a été déposé dans l'environnement")
robot.getOrientation()
robot.getPos()
env.afficheTab()
print()

print("Test des méthodes tourner et avanver de Objet")
robot.avancer(env,10)
robot.getPos()
print()
robot.tourner("bas")
robot.avancer(env,2)
robot.getPos()
env.afficheTab()
print()
robot.tourner("gauche")
robot.avancer(env,4)
print()
robot.tourner("haut")
robot.avancer(env,2)
robot.getPos()
env.afficheTab()
print()
robot.tourner("droite")
robot.avancer(env,7)
robot.getPos()
env.afficheTab()
print()

print("Test des méthodes tourner et reculer de Objet")
robot.reculer(env,2)
robot.getPos()
robot.getOrientation()
env.afficheTab()
print()
robot.tourner("haut")
robot.reculer(env,10)
robot.getPos()
print()
robot.tourner("bas")
robot.reculer(env,8)
robot.getPos()
print()
robot.tourner("gauche")
robot.reculer(env,4)
robot.getPos()
env.afficheTab()
print()
robot.tourner("droite")
robot.reculer(env,10)
robot.getPos()
print()
